# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- releases/*

stages:
  - stage: MAT
    jobs:
      - job: MAT
        condition: and(not(eq(variables['skip_MAT'], 'true')), not(eq(variables['isEliteBuds'], 'true')))
        displayName: MAT
        pool: "Default"
        steps:
          #Run MAT test using Maven command
          - task: CmdLine@2
            displayName: "Executing MAT"
            inputs:
              script: |
                cd $(Build.Repository.LocalPath)
                mvn clean test -DdefaultSuiteFile=TestSuite/TestSuite_ComCent_Registration.xml -e -U